### ISSUE TITLE
使用WikiPlus进行编辑会带网页源代码

### ISSUE THREAD

**Issue by Honglan233** [Wikiplus/Wikiplus#119]
我在我的网站上将WikiPlus设置为小工具，代码见https://www.gengbaike.top/wiki/MediaWiki:Gadget-WikiPlus.js
用户将WikiPlus启用后编辑页面会带网页的源代码
![Uploading Screenshot_20240501_134901_com.android.chrome.jpg…](这是原先的条目内容)
![Uploading Screenshot_20240501_134915_com.android.chrome.jpg…](这是WikiPlus显示的条目内容)

**Comment by Last-Order** [comment]
hello你的图片没有上传成功哦

**Comment by Honglan233** [comment]
> hello你的图片没有上传成功哦

![条目原内容](https://github.com/Wikiplus/Wikiplus/assets/81944129/8f1f4f23-6d2d-4db3-9c1e-17e1215fda03)
![使用WikiPlus打开显示的内容](https://github.com/Wikiplus/Wikiplus/assets/81944129/0a3d27f3-f572-4bb0-829e-b21d3da82e98)

**Comment by Last-Order** [comment]
站点是不是配置了什么重定向规则？
举个例子
`https://www.gengbaike.top/w/index.php?oldid=5171&section=&action=raw` 被重定向到了
`https://www.gengbaike.top/wiki/?oldid=5171`
并且参数丢失了

**Comment by greatestlove521** [comment]
@Last-Order 
https://cnmusic.miraheze.org/wiki/MediaWiki:Gadget-Wikiplus.js
fork了一个版本，修改URL参数之后，Miraheze上终于能用了，但是也只能编辑全文而已，章节标题右侧无法出现“快速编辑”按钮。

**Comment by greatestlove521** [comment]
@Last-Order @Honglan233 
https://cnmusic.miraheze.org/wiki/MediaWiki:Gadget-Wikiplus.js?diff=1558&oldid=1482
修改表达式之后目前可以正常使用了，这个fork的版本可以在Miraheze上运行，示例：https://cnmusic.miraheze.org/wiki/%E6%AD%8C%E6%89%8B2024?diff=prev&oldid=1560

**Comment by Honglan233** [comment]
已解决
