### ISSUE TITLE
【建议】为外部链接的编辑增加快速编辑按钮。

### ISSUE THREAD

**Issue by zyzsdy** [Wikiplus/Wikiplus#20]
在萌娘百科的讨论[【推广】建议推广{{指定页面编辑按钮}}](http://zh.moegirl.org/Talk:%E8%AE%A8%E8%AE%BA%E7%89%88#.E3.80.90.E6.8E.A8.E5.B9.BF.E3.80.91.E5.BB.BA.E8.AE.AE.E6.8E.A8.E5.B9.BF.7B.7B.E6.8C.87.E5.AE.9A.E9.A1.B5.E9.9D.A2.E7.BC.96.E8.BE.91.E6.8C.89.E9.92.AE.7D.7D)中，对[模板:指定页面编辑按钮](http://zh.moegirl.org/Template:%E6%8C%87%E5%AE%9A%E9%A1%B5%E9%9D%A2%E7%BC%96%E8%BE%91%E6%8C%89%E9%92%AE)的使用会在页面上留下一个形如`[编辑]`的链接。建议为每个这样的链接增加快速编辑的功能。

从实现原理上，可以简单的在href值符合`title=(.+)&action=edit`的a标签在后面增加快速编辑，链接到这个串中的`$1`部分即可。

**Comment by Last-Order** [comment]
了解，我看看-v-

**Comment by Last-Order** [comment]
还有bug
