### ISSUE TITLE
可拖动热区是不是太小

### ISSUE THREAD

**Issue by zyzsdy** [Wikiplus/Wikiplus#33]
终于可以拖动了。。。

终于不用为了看被编辑框挡住的部分再开一个页面了。。。。。

下面是问题：

开始拖动的热区是不是太小了。我感觉只有顶栏的一半高度，而且在“快速编辑”这四个字的地方并不能拖动。

反正“快速编辑”也不能改，直接在上面盖一层看不见的div，全部设置成拖动热区怎么样。

**Comment by Last-Order** [comment]
有效区域是Header部分。。盖一层也行啊。。我周末改改……

**Comment by Last-Order** [comment]
a06e1af7b63bdb7cf17374a138b138a990b555a0
