### ISSUE TITLE
多主题支持

### ISSUE THREAD

**Issue by zyzsdy** [Wikiplus/Wikiplus#35]
目前只支持Vector主题。

长远来看应该做统一适配或者各主题适配。

（该issue是从[Wikipedia的讨论页](https://zh.wikipedia.org/wiki/Topic:St8aw5gzr2g6ezde)提出的）

**Comment by Last-Order** [comment]
除vector之外的皮肤，使用人数已经很少了。感觉Mediawiki官方也放弃这些古老的皮肤了。为了适配这少量用户增加文件体积，感觉有些得不偿失。

**Comment by zyzsdy** [comment]
。。。。。。。。
其实我在wikipedia用的就不是vector。。。。。。
为了装wikiplus前天刚换的vector。

感觉老用户应该对monobook更喜欢一点吧。。

好吧扯远了

我认为mediawiki既然有这个“皮肤”系统。
那么在每个皮肤中生成这个需要的“编辑”按钮都是按照一个和皮肤无关的方式去生成的。

我们应该找到一般规律，而不是像现在这样，实际上是你hack了vector的html。

虽然Wikipedia现在还是以vector为主了，但是mediawiki在不止是Wikipedia的地方，还有很多其他的以mediawiki搭建的站点，各自使用了不同的皮肤来做个性化。

我觉得Wikiplus既然要支持多维基，而不是有限列表中的几个维基，mediawiki既然有皮肤系统，只对其中的一款皮肤做适配并不是很厚道。

不过确实，大量的mediawiki系统都在使用vector皮肤。

**Comment by Last-Order** [comment]
然而节点的名字是皮肤自己定义的……并没有一般规律。要支持太繁杂了……( •ิ_• ิ)

**Comment by zyzsdy** [comment]
好吧。我去了解了一下。
我同意。。。

**Comment by liangent** [comment]
那个编辑按钮不都是 .mw-editsection 嘛……

然后，顶上的编辑标签请用mw.util.addPortletLink()而不要自己构建

等等

**Comment by Last-Order** [comment]
@liangent 我还真不知道这个……那可以一做

**Comment by Last-Order** [comment]
mw.util.addPortletLink()是sidebar的按钮……来着。然后我看到了https://doc.wikimedia.org/mediawiki-core/master/js/#!/api/mw.toolbar mw.toolbar似乎可以解决，然而在最新的mediawiki版本上都没有定义这个方法= =……真是服了，等有生之年再完成这个功能吧。issue先关了，有解决方案再说。
