### ISSUE TITLE
希望在编辑框中能使用一些高级编辑特性

### ISSUE THREAD

**Issue by zyzsdy** [Wikiplus/Wikiplus#39]
最需要的是按Tab键插入制表符。

此外还有：
按Shift+Tab键删除本行的第一个制表符
选中多行文字后按Tab键将会给选中的每一行都加上制表符
选中多行文字后按Shift+Tab键将会删除选中的每一行的第一个制表符

选中文字后按Ctrl+B加粗
选中文字后按Ctrl+I斜体
选中文字后按Ctrl+U添加下划线

【萌百专用】选中文字后按Ctrl+Shift+B添加黑幕

等等等等。。。。。。。。

**Comment by Last-Order** [comment]
。。。论插件系统的重要性

**Comment by liangent** [comment]
先直接看看能不能把WikiEditor/CodeEditor应用进来吧。。

**Comment by Last-Order** [comment]
本issue转由Wikiplus-3.0实现。
