### ISSUE TITLE
希望Wikiplus的编辑框可以支持代码着色。

### ISSUE THREAD

**Issue by zyzsdy** [Wikiplus/Wikiplus#40]
快速编辑框也可以代码着色，这样可以方便的找出是不是模板已经全部正确的闭合了。

**Comment by Last-Order** [comment]
这样就太重了……本来wikiplus就是给改动不大的编辑使用的，还是不建议用来处理复杂的事务。这个可以做成插件(ಥ_ಥ)

**Comment by Last-Order** [comment]
本issue转由Wikiplus-3.0实现。
