### ISSUE TITLE
新版本无法新建页面

### ISSUE THREAD

**Issue by zyzsdy** [Wikiplus/Wikiplus#48]
当前版本的wikiplus在最新版本的mediawiki上无法新建页面。
报错信息如下：
![image](https://cloud.githubusercontent.com/assets/5925733/11657062/bb85115c-9df4-11e5-8ca6-0fa9241467fe.png)
![image](https://cloud.githubusercontent.com/assets/5925733/11657075/ca64c01e-9df4-11e5-880e-9b6d3a8ac8d4.png)

似乎2.0都不能用来新建页面？

**Comment by Last-Order** [comment]
3f60a18365e490f8f58dbf4d96e07f367547019c
