### ISSUE TITLE
中文維基人 SzMithrandir 說，英語譯文太爛。

### ISSUE THREAD

**Issue by LNDDYL** [Wikiplus/Wikiplus#53]
https://github.com/Wikiplus/Wikiplus/blob/master/languages/en-us.json

**Comment by Last-Order** [comment]
希望给出一些建议以修正。

**Comment by Jasonzhuocn** [comment]
在 https://tools.wmflabs.org/guc/?user=SzMithrandir
沒看到那位先生留下使用過wikiplus的編輯摘要，
common.js歷史版本或meta的global.js也沒有使用過 wikiplus 的痕跡

**Comment by LNDDYL** [comment]
@Jasonzhuocn 我找了SzMithrandir幫忙，他看了下English譯文，表示道：有幾處英文單詞拼寫有誤，語法也很蹩腳。

**Comment by Last-Order** [comment]
@LNDDYL 具体指出一下？

**Comment by Last-Order** [comment]
如无具体意见，关闭issue处理。
