### ISSUE TITLE
我想加入到你們的團隊

### ISSUE THREAD

**Issue by LNDDYL** [Wikiplus/Wikiplus#57]
https://github.com/orgs/Wikiplus/people
只負責管理譯文。
可否？

**Comment by Last-Order** [comment]
加入组织并不会给你带来什么便利。而即使不加入组织，你的贡献都会被commit记录，请放心。
鉴于权限不能只限定在语言文件的管理，以及你似乎不大熟悉JavaScript，很抱歉我和@zyzsdy 都不能同意将你加入组织。

**Comment by Last-Order** [comment]
若要更新语言文件，请大胆提交Pull Request，我们将会很快处理。

**Comment by LNDDYL** [comment]
好吧…
