### ISSUE TITLE
安装Wikiplus 您是否允许Wikiplus采集非敏感数据用于改进Wikiplus及为当前Wiki: Wikipedia 提供改进建议?

### ISSUE THREAD

**Issue by LNDDYL** [Wikiplus/Wikiplus#58]
這部分似乎沒有進行多語言處理。

**Comment by LNDDYL** [comment]
我設定的系統語言是zh-TW，但在Wikiplus上面仍然出現簡體字。

**Comment by Last-Order** [comment]
首次安装时由于网络原因可能还没来得及获取语言文件并建立缓存，有可能无法正常处理，刷新一下，问题还存在吗？

**Comment by Last-Order** [comment]
由于未有回应，暂作关闭处理，如有问题请重新打开。

**Comment by LNDDYL** [comment]
我不太想開新issue，我就在這裡講了。
預設簡體對話方塊(zh-cn dialog)這個問題，至今為止仍未解決。

**Comment by Last-Order** [comment]
很抱歉，最近无法解决您的问题。

LNDDYL <notifications@github.com>于2016年3月20日周日 13:41写道：

**Comment by zyzsdy** [comment]
该问题将不会修复。

将在Wikiplus-3.0中彻底解决。

**Comment by LNDDYL** [comment]
Wikiplus-3.0的繁中語系檔需要重新譯（捂臉）
