### ISSUE TITLE
在VE启用的MediaWiki站点上，用户讨论页的二级标题后链接不正常

### ISSUE THREAD

**Issue by ryRubyy** [Wikiplus/Wikiplus#66]
具体情况是，在用户讨论页二级标题（也就是每条留言）的右侧编辑链接变成了 `[ | 编辑源代码 | QuickEdit ]`。

开启了 VisualEditor 功能， 浏览器使用的是 TorBrowser（所以被封禁不能编辑）。

审查元素看到的结果是，前面本应该有一个 `class="mw-editsection-visualeditor"` 的 “编辑源代码”，不过在`.ve-not-available .mw-editsection-visualeditor` 的 CSS 中被 `display:none`掉了。于是分隔线就变得有点奇怪。

不知道是 VE 的锅还是 Wikiplus 的锅，没试过关闭 W+ 复现（因为被封禁连`common.js`都编辑不了），也没在别的站点试过（萌百似乎并没有VE...）。

（如果是 VE 的锅估计得报 [phab](https://phabricator.wikimedia.org/maniphest/task/create/?projects=visualeditor) 了...）

**Comment by Last-Order** [comment]
呃……稍后确认一下。

**Comment by Last-Order** [comment]
Wikiplus 加入段落编辑的逻辑为：
寻找到`.mw-editsection`中的最后一个`.mw-editsection-bracket`，然后向前插入一个编辑按钮。理论上来讲不会在`.mw-editsection-visualeditor`后加一个分隔符。参见https://github.com/Wikiplus/Wikiplus/blob/master/src/Main.js#L999

我账号是IP封禁豁免，暂时无法复现你说的环境。不过我感觉可能是 VE 那边的问题。

Feel free to repoen this issue.
