### ISSUE TITLE
Urdu translation

### ISSUE THREAD

**Issue by yethrosh** [Wikiplus/Wikiplus#69]
Urdu translations added but not applied. I am using wiki-plus on Urdu wikipedia where wikiplus still appears in english.
And one more thing, an edit summary "Edit via wiki plus" appears in english and not provided for localisation.

**Comment by Last-Order** [comment]
1. New version will be published soon. Please give me some time to do tests.

2. Current version doesn't support localisation of the default summary. I will add it in next version. Thanks for your report.

**Comment by Last-Order** [comment]
Localisation of default summary suffix is now supported. Perhaps you can update language files now.

**Comment by yethrosh** [comment]
Updated, thanks.
