### ISSUE TITLE
MinorEdit

### ISSUE THREAD

**Issue by Tiger3018** [Wikiplus/Wikiplus#71]
当参数设置为“默认标记所有编辑为小编辑”时，小编辑的选项打不打勾都会是小编辑。
希望可以能让**表单的最终状态**强制覆盖默认参数。
```
    if ($('#Wikiplus-Quickedit-MinorEdit').is(':checked')) {
        addtionalConfig['minor'] = 'true';
    }
    else {
        addtionalConfig['minor'] = 'false';
    }
```
（示意）

**Comment by Last-Order** [comment]
根据 MediaWiki API 手册关于数据类型的说明，minor 参数的类型为 boolean，需要设置它为 false 的时候必须不带这个参数。这个问题可能无法解决。

参见：https://www.mediawiki.org/w/api.php?action=help&modules=main#main/datatypes

**Comment by Tiger3018** [comment]
可以这样：
```
addtionalConfig['notminor'] = 'true';
```
见 https://zh.wikipedia.org/wiki/MediaWiki:Gadget-morebits.js 中注释``force Twinkle config to override user preference setting for "all edits are minor"``

**Comment by Tiger3018** [comment]
已解决，感谢。
