### ISSUE TITLE
使用回复工具进行回复后的问题

### ISSUE THREAD

**Issue by AnYiLin** [Wikiplus/Wikiplus#85]
维基最近开发了一个回复工具，Wikiplus在页面中插入的按钮会在回复之后消失，因为这个回复工具会把页面正文内容全文提交再重新渲染一次，解决方法是 https://github.com/Xi-Plus/twinkle/commit/70868560bb1d7ac3ea3e269e7a02e680a1879046 加个hook。

**Comment by AnYiLin** [comment]
@Last-Order 没在dev里改，您有时间需要自己合并一下。

**Comment by Last-Order** [comment]
好的我迟一点处理
