### ISSUE TITLE
使用回复工具进行回复后的页面版本问题

### ISSUE THREAD

**Issue by AnYiEE** [Wikiplus/Wikiplus#89]
@Last-Order：刚刚发现虽然让Wikiplus支持了回复工具，但因为回复工具在某章节回复后会直接插入DOM而不会刷新页面，于是就发生了这个问题。

复现流程是：使用回复工具在A章节回复，使用Wikiplus编辑此章节，提示编辑冲突。

应该是`init`函数GET到的`basetimestamp`和之后POST时的对不上，这时间戳我就不熟了…还是麻烦您看一下。

PS：去掉POST时的basetimestamp参数就可以正常提交。

**Comment by AnYiLin** [comment]
看了一下，后文所有的oldid都在`initQuickEditInterface`函数中定义，那么只需要将这部分拿出来，放到之前加的`mw.hook`里就可以了。

**Comment by AnYiLin** [comment]
> 看了一下，后文所有的oldid都在`initQuickEditInterface`函数中定义，那么只需要将这部分拿出来，放到之前加的`mw.hook`里就可以了。

或者干脆不存成变量，每次都重新取。

**Comment by Last-Order** [comment]
感觉有点危险 这种很容易造成编辑冲突或者其他问题 得仔细考虑下

**Comment by AnYiLin** [comment]
> 感觉有点危险 这种很容易造成编辑冲突或者其他问题 得仔细考虑下

肯定是危险的，所以不能去掉。

回复A章节后再编辑A章节会出现这个问题，但编辑B章节就不会，明明二者有同一个`oldid`。这个时间戳是根据什么生成的呢？

**Comment by Last-Order** [comment]
`oldid`是页面的版本ID，Wikiplus目前会提交旧的`oldid`，编辑A章节后再编辑A章节，Mediawiki 知道A章节在这个`oldid`之后被更改过所以会编辑冲突，而B章节未被更改所以放行。（所以 MediaWiki 的编辑冲突控制以章节为粒度）

**Comment by AnYiLin** [comment]
> `oldid`是页面的版本ID，Wikiplus目前会提交旧的`oldid`，编辑A章节后再编辑A章节，Mediawiki 知道A章节在这个`oldid`之后被更改过所以会编辑冲突，而B章节未被更改所以放行。（所以 MediaWiki 的编辑冲突控制以章节为粒度）

可能是我没说明白。

现在的情况是，比如原始`oldid`是`1`，页面内容和Wikiplus取到的页内容都为`a`；使用回复工具在A章节回复后，回复工具会更新JS API`mw.config.get`取到的`oldid`至`2`，此时页面内容为`b`。

这时再用Wikiplus编辑同章节，可以获取到正确的页面内容`b`，`oldid`也为`2`。但提交的时候，会提交错误的时间戳，服务器返回“编辑冲突”。

**Comment by Last-Order** [comment]
我知道你的意思，也知道原因，也知道怎么修
但是就是这个改动需要考虑一下会不会有其他影响，不急
