### ISSUE TITLE
提交编辑时的令牌问题

### ISSUE THREAD

**Issue by AnYiEE** [Wikiplus/Wikiplus#90]
现在Wikiplus在同页面编辑时会先获取JS API提供的CSRF token，获取不到会请求网络API。

请问可不可以加个逻辑：用JS API提供的CSRF token提交编辑失败之后，如果返回的是错误1038，就尝试用网络API获取一次，自动重新提交，如果再失败才抛异常。因为令牌失效很可能就是单纯的超时（刚刚遇到的…）

上述逻辑类似[mw.Api.postWithEditToken()](https://doc.wikimedia.org/mediawiki-core/master/js/source/index6.html#mw-Api-method-postWithToken)，或者干脆就用mw.Api好了…`await mw.loader.using('mediawiki.api')`。

**Comment by Last-Order** [comment]
其实Wikiplus的设计意图是快速编辑一些小的更改，不鼓励进行长时间的复杂修改（

**Comment by AnYiLin** [comment]
> 其实Wikiplus的设计意图是快速编辑一些小的更改，不鼓励进行长时间的复杂修改（

~~你永远猜不到用户会怎么用你的产品~~
