### ISSUE TITLE
非自动确认用户增加错误提示

### ISSUE THREAD

**Issue by Last-Order** [Wikiplus/Wikiplus#92]
啊对了，今晚维基QQ大群里有新人问怎么点快速编辑不出窗口，别人再转述问小群里的我
来来回回好一会儿，怎么说呢…建议用那个Moenotice前台提示一下用户不是非自确，不要只在控制台里报错…

_Originally posted by @AnYiLin in https://github.com/Wikiplus/Wikiplus/issues/91#issuecomment-902067878_

**Comment by AnYiLin** [comment]
https://github.com/Wikiplus/Wikiplus/pull/93
