### ISSUE TITLE
Request: Multi-License

### ISSUE THREAD

**Issue by xaosflux** [Wikiplus/Wikiplus#98]
Hello!

This is a request to additionally license your project in addition to the Adobe v2 license.

Would you consider making your code available under the:

Commons:Creative Commons Attribution-ShareAlike 3.0 Unported License
 <https://en.wikipedia.org/wiki/Wikipedia:Text_of_Creative_Commons_Attribution-ShareAlike_3.0_Unported_License>

Thank you for your consideration!

**Comment by xaosflux** [comment]
Hello,

The reason for the ask is a debate that is currently occurring on projects
such as Wikipedia.  The summary is that Wikipedia requires that all
published pages are published under certain licenses (such as CC-BY-SA 3).
The normal use case for using this wonderful script is to copy it to a
wikipage that will be executed client-side automatically by users.  The
debate is that when the code is copied to a Wikipedia page, that a license
violation is occurring, as Apache v2 is not compatible with CC-BY-SA-3,
however the code is now publicly available to readers of the copied page.
This matter is not settled, but this ask was to avoid telling users not to
use Wikiplus - as they would surely miss it!

Thank you for your engagement!

**Comment by Last-Order** [comment]
Thanks for your explanation. I have added CC BY-SA 3.0 license to Wikiplus. (See master branch. Will be also applied to the dev branch later) Please feel free to use it.

**Comment by xaosflux** [comment]
Thank you!
